# Generated by Django 2.1.3 on 2018-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sesion_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
