# Generated by Django 2.1.3 on 2018-11-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181126_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cost',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
