# Generated by Django 2.1.3 on 2018-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20181127_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
